name: InstaPerms
author: BoxOfDevs Team
authors:
- TheDragonRing
- Ad5001
version: 1.0.0
description: The instant permissions manager that really is instant!
api:
- 1.0.0
- 2.0.0
main: InstaPerms\Main
load: STARTUP
commands:
    setperm:
        usage: "/setperm <player> <permission>"
        description: "Gives a player a permission"
        permission: instaperms.set
    rmperm:
        usage: "/rmperm <player> <permission>" 
        description: "Removes a players permission"
        permission: instaperms.rm
    hasperm:
        usage: "/hasperm <player> <permission>"
        description: "Checks if a player has a permission"
        permission: instaperms.has
    seeperms:
        usage: "/seeperms <player>"
        description: "Shows all a players permissions"
        permission: instaperms.see
permissions:
    instaperms:
        default: false
        children:
            instaperms.set:
                default: op
            instaperms.rm:
                default: op
            instaperms.has:
                default: op
            instaperms.see:
                default: op
